### ISSUE TITLE
pry won't start on 1.9.3-p392

### ISSUE THREAD

**Issue by ivanoats** [nixme/pry-debugger#24]
```
~  gem install pry-debugger                                                                                                                                    
Fetching: pry-debugger-0.2.1.gem (100%)
Successfully installed pry-debugger-0.2.1
1 gem installed
Installing ri documentation for pry-debugger-0.2.1...
Building YARD (yri) index for pry-debugger-0.2.1...
Installing RDoc documentation for pry-debugger-0.2.1...
leaf ➜  ~  pry                                                                                                                                                         /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:11: warning: already initialized constant DEFAULT_HOOKS
/Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:17: warning: already initialized constant DEFAULT_PRINT
/Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:55: warning: already initialized constant SIMPLE_PRINT
/Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:64: warning: already initialized constant CLIPPED_PRINT
/Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:69: warning: already initialized constant DEFAULT_EXCEPTION_HANDLER
/Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:78: warning: already initialized constant DEFAULT_PROMPT_NAME
/Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:81: warning: already initialized constant DEFAULT_PROMPT
/Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:92: warning: already initialized constant SIMPLE_PROMPT
/Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:94: warning: already initialized constant SHELL_PROMPT
/Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:101: warning: already initialized constant NAV_PROMPT
/Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:116: warning: already initialized constant DEFAULT_CONTROL_D_HANDLER
/Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:132: warning: already initialized constant DEFAULT_SYSTEM
/Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:140: warning: already initialized constant INITIAL_PWD
/Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:185: warning: already initialized constant DEFAULT_EXCEPTION_WHITELIST
/Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry/cli.rb:7: warning: already initialized constant NoOptionsError
/Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require': cannot load such file -- trace_nums (LoadError)
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/debugger-linecache-1.1.2/lib/tracelines19.rb:3:in `<top (required)>'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/debugger-linecache-1.1.2/lib/linecache19.rb:65:in `<top (required)>'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/debugger-1.2.4/lib/ruby-debug-base.rb:2:in `<top (required)>'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/debugger-1.2.4/lib/ruby-debug.rb:5:in `<top (required)>'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/debugger-1.2.4/lib/debugger.rb:4:in `<top (required)>'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-debugger-0.2.1/lib/pry-debugger/processor.rb:2:in `<top (required)>'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-debugger-0.2.1/lib/pry-debugger/pry_ext.rb:2:in `<top (required)>'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-debugger-0.2.1/lib/pry-debugger/cli.rb:14:in `<top (required)>'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry/plugins.rb:38:in `load_cli_options'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry/cli.rb:39:in `block in add_plugin_options'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry/cli.rb:38:in `each'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry/cli.rb:38:in `add_plugin_options'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry/cli.rb:94:in `<top (required)>'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/lib/pry.rb:267:in `<top (required)>'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/bin/pry:12:in `rescue in <top (required)>'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/gems/pry-0.9.12/bin/pry:8:in `<top (required)>'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/bin/pry:19:in `load'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/bin/pry:19:in `<main>'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/ivan/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
leaf ➜  ~  gem uninstall pry-debugger                                                                                                                                  18:31 ivan
Successfully uninstalled pry-debugger-0.2.1
leaf ➜  ~  pry                                                                                                                                                         18:32 ivan
[1] pry(main)>
```

**Comment by nixme** [comment]
Upgrade `debugger`: `gem install debugger`

See https://github.com/cldwalker/debugger/issues/52 for more details.

**Comment by nixme** [comment]
Closing. I've updated the debugger dependency, make sure you're using the latest one.
