### ISSUE TITLE
malloc: possible integer overflow (ArgumentError)

### ISSUE THREAD

**Issue by kyrylo** [nixme/pry-debugger#36]
### Environment

```
ruby 1.9.3p392 (2013-02-22 revision 39386) [i686-linux]
Pry version 0.9.12.1 on Ruby 1.9.3
```
### Steps to reproduce

```
gem install pry-debugger
pry
```

Output.

```
Fetching: debugger-ruby_core_source-1.2.0.gem (100%)
Fetching: debugger-linecache-1.2.0.gem (100%)
Fetching: debugger-1.5.0.gem (100%)
Building native extensions.  This could take a while...
Fetching: pry-debugger-0.2.2.gem (100%)
Successfully installed debugger-ruby_core_source-1.2.0
Successfully installed debugger-linecache-1.2.0
Successfully installed debugger-1.5.0
Successfully installed pry-debugger-0.2.2
4 gems installed
/opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': malloc: possible integer overflow (ArgumentError)
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/curacao/.gem/ruby/1.9.3/gems/debugger-1.5.0/lib/ruby-debug-base.rb:1:in `<top (required)>'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/curacao/.gem/ruby/1.9.3/gems/debugger-1.5.0/lib/ruby-debug.rb:5:in `<top (required)>'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/curacao/.gem/ruby/1.9.3/gems/debugger-1.5.0/lib/debugger.rb:4:in `<top (required)>'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/curacao/.gem/ruby/1.9.3/gems/pry-debugger-0.2.2/lib/pry-debugger/processor.rb:2:in `<top (required)>'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/curacao/.gem/ruby/1.9.3/gems/pry-debugger-0.2.2/lib/pry-debugger/pry_ext.rb:2:in `<top (required)>'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/curacao/.gem/ruby/1.9.3/gems/pry-debugger-0.2.2/lib/pry-debugger/cli.rb:14:in `<top (required)>'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/curacao/.gem/ruby/1.9.3/gems/pry-0.9.12.1/lib/pry/plugins.rb:38:in `load_cli_options'
        from /home/curacao/.gem/ruby/1.9.3/gems/pry-0.9.12.1/lib/pry/cli.rb:39:in `block in add_plugin_options'
        from /home/curacao/.gem/ruby/1.9.3/gems/pry-0.9.12.1/lib/pry/cli.rb:38:in `each'
        from /home/curacao/.gem/ruby/1.9.3/gems/pry-0.9.12.1/lib/pry/cli.rb:38:in `add_plugin_options'
        from /home/curacao/.gem/ruby/1.9.3/gems/pry-0.9.12.1/lib/pry/cli.rb:94:in `<top (required)>'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/curacao/.gem/ruby/1.9.3/gems/pry-0.9.12.1/lib/pry.rb:267:in `<top (required)>'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /opt/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/curacao/.gem/ruby/1.9.3/gems/pry-0.9.12.1/bin/pry:9:in `<top (required)>'
        from /home/curacao/.gem/ruby/1.9.3/bin/pry:23:in `load'
        from /home/curacao/.gem/ruby/1.9.3/bin/pry:23:in `<main>'
```
### Additional information

With the older version of Pry Debugger everything works fine.

```
gem install pry-debugger -v 0.2.1
```

**Comment by kyrylo** [comment]
OK, I'm not sure what's going on, but I uninstalled all my gems and installed only the required ones. And the problem has disappeared.
