### ISSUE TITLE
Fails to install on Ruby 2.1.2p95: Failed to build gem native extension

### ISSUE THREAD

**Issue by Lordnibbler** [nixme/pry-debugger#52]
```
Installing debugger-linecache 1.2.0
Installing debugger-ruby_core_source 1.3.2

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /.rbenv/versions/2.1.2/bin/ruby extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/.rbenv/versions/2.1.2/bin/ruby
/.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:1573:in `stat': No such file or directory @ rb_file_s_stat - ./212/ruby_debug.h (Errno::ENOENT)
        from /.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:1573:in `block in fu_each_src_dest'
        from /.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:1587:in `fu_each_src_dest0'
        from /.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:1571:in `fu_each_src_dest'
        from /.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:399:in `cp'
        from extconf.rb:83:in `block in <main>'
        from extconf.rb:82:in `each'
        from extconf.rb:82:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /vendor/bundler/gems/debugger-1.6.6 for inspection.
Results logged to /vendor/bundler/extensions/x86_64-darwin-13/2.1.0-static/debugger-1.6.6/gem_make.out
An error occurred while installing debugger (1.6.6), and Bundler cannot continue.
Make sure that `gem install debugger -v '1.6.6'` succeeds before bundling.
```

**Comment by jonathanpa** [comment]
Same for me with rbenv, ruby 2.1.2p95 on Archlinux. By waiting a fix, you can use instead https://github.com/deivid-rodriguez/pry-byebug

**Comment by GriwMF** [comment]
tnx, byebug works fine! In my case error was with pry-debugger on Archlinux also

**Comment by nixme** [comment]
Newever versions of debugger-ruby_core_source should compile fine with Ruby 2.1.2.

But as mentioned, for proper navigation behavior switch to `pry-byebug` on MRI 2+
