### ISSUE TITLE
Unable to install with ruby version 2.1.4

### ISSUE THREAD

**Issue by jonyt** [nixme/pry-debugger#59]
hi,

I can't seem to install pry-debugger with ruby 2.1.4. Downgrading to 2.0.0 helps. This is on Kubuntu 14.04. Here's what I'm getting:

```
Installing debugger-ruby_core_source 1.3.7

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /home/jonyt/.rvm/rubies/ruby-2.1.4/bin/ruby -r ./siteconf20141202-9696-11gyj8z.rb extconf.rb 
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/home/jonyt/.rvm/rubies/ruby-2.1.4/bin/ruby
/home/jonyt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1401:in `initialize': No such file or directory @ rb_sysopen - ./214/ruby_debug.h (Errno::ENOENT)
    from /home/jonyt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1401:in `open'
    from /home/jonyt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1401:in `copy_file'
    from /home/jonyt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:483:in `copy_file'
    from /home/jonyt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:400:in `block in cp'
    from /home/jonyt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1579:in `block in fu_each_src_dest'
    from /home/jonyt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1593:in `fu_each_src_dest0'
    from /home/jonyt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1577:in `fu_each_src_dest'
    from /home/jonyt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:399:in `cp'
    from extconf.rb:83:in `block in <main>'
    from extconf.rb:82:in `each'
    from extconf.rb:82:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/jonyt/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/gems/debugger-1.6.8 for inspection.
Results logged to /home/jonyt/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/debugger-1.6.8/gem_make.out
An error occurred while installing debugger (1.6.8), and Bundler cannot
continue.
Make sure that `gem install debugger -v '1.6.8'` succeeds before bundling.
```

**Comment by nixme** [comment]
As the README notes, please use `pry-byebug` on MRI 2+: https://github.com/deivid-rodriguez/pry-byebug
