### ISSUE TITLE
`require': cannot load such file -- pry-debugger (LoadError)

### ISSUE THREAD

**Issue by sginsbourg** [nixme/pry-debugger#63]
C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pry-debugger (LoadError)
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from convert.rb:6:in `<main>'

source: http://elementalselenium.com/tips/68-load-testing-revisited

**Comment by sginsbourg** [comment]
gem install pry-debugger
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing pry-debugger:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/debugger-1.6.8/ext/ruby_debug
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20180928-5272-4n0rdn.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby24-x64/bin/$(RUBY_BASE_NAME)
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1289:in `initialize': No such file or directory @ rb_sysopen - ./244/ruby_debug.h (Errno::ENOENT)
        from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1289:in `open'
        from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1289:in `copy_file'
        from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:430:in `copy_file'
        from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:357:in `block in cp'
        from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1461:in `block in fu_each_src_dest'
        from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1475:in `fu_each_src_dest0'
        from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1459:in `fu_each_src_dest'
        from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:356:in `cp'
        from extconf.rb:83:in `block in <main>'
        from extconf.rb:82:in `each'
        from extconf.rb:82:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/debugger-1.6.8 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/debugger-1.6.8/gem_make.out
